# Generated by Django 4.2.7 on 2023-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='departamento',
            field=models.CharField(choices=[('Piezas', 'Piezas'), ('Drones', 'Drones'), ('Accesorios', 'Accesorios')], max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(choices=[('DJI', 'DJI'), ('Parrot', 'Parrot'), ('Yuneec', 'Yuneec'), ('Autel', 'Autel'), ('3DR', '3DR'), ('Skydio', 'Skydio'), ('Walkera', 'Walkera'), ('PowerVision', 'PowerVision'), ('Hubsan', 'Hubsan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='seccion',
            field=models.CharField(choices=[('Electronico', 'Electronico'), ('No-Electronico', 'No-Electronico'), ('Carga', 'Carga'), ('Vigilancia', 'Vigilancia'), ('Fotografia', 'Fotografia'), ('Videografia', 'Videografia'), ('Cuadricoptero', 'Cuadricoptero'), ('Hexacoptero', 'Hexacoptero'), ('Agricola', 'Agricola'), ('Recopilador', 'Recopilador'), ('Envio', 'Envio')], max_length=255),
        ),
    ]
