# Generated by Django 4.2.7 on 2023-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_producto_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='seccion',
            field=models.CharField(choices=[('Electronico', 'Electronico'), ('Analogico', 'Analogico'), ('Carga', 'Carga'), ('Vigilancia', 'Vigilancia'), ('Fotografia', 'Fotografia'), ('Videografia', 'Videografia'), ('Cuadricoptero', 'Cuadricoptero'), ('Hexacoptero', 'Hexacoptero'), ('Agricola', 'Agricola'), ('Recopilador', 'Recopilador'), ('Envio', 'Envio')], max_length=255),
        ),
    ]
