# Generated by Django 3.2.23 on 2023-12-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_opinion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='texto',
            new_name='mensaje',
        ),
    ]
