<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-23 22:34

from django.db import migrations, models
=======
# Generated by Django 4.2.5 on 2023-11-23 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 6d48e0ebf00b82aa947d5f1864eb8572424fef8f


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 6d48e0ebf00b82aa947d5f1864eb8572424fef8f
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('puerta', models.CharField(max_length=255)),
                ('codigo_postal', models.IntegerField()),
                ('provincia', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=255)),
                ('numero_tarjeta', models.CharField(max_length=255)),
                ('caducidad', models.CharField(max_length=255)),
                ('cs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=255)),
=======
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 6d48e0ebf00b82aa947d5f1864eb8572424fef8f
            ],
        ),
    ]
