# Generated by Django 3.2.23 on 2023-11-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('puerta', models.CharField(max_length=255)),
                ('codigo_postal', models.IntegerField()),
                ('provincia', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=255)),
                ('numero_tarjeta', models.CharField(max_length=255)),
                ('caducidad', models.CharField(max_length=255)),
                ('cs', models.IntegerField()),
            ],
        ),
    ]
