# Generated by Django 3.2.23 on 2023-12-03 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mensajereclamacion_reclamacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
