# Generated by Django 3.2.23 on 2023-12-03 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_reclamacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajereclamacion',
            name='user',
        ),
        migrations.AddField(
            model_name='mensajereclamacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
