# Generated by Django 3.2.23 on 2023-12-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20231203_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacion',
            name='mensajes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
