# Generated by Django 3.2.23 on 2023-12-03 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_reclamacion_mensajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
