# Generated by Django 4.2.5 on 2023-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20231203_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_pago',
            name='caducidad',
        ),
        migrations.RemoveField(
            model_name='datos_pago',
            name='cs',
        ),
        migrations.RemoveField(
            model_name='datos_pago',
            name='numero_tarjeta',
        ),
        migrations.RemoveField(
            model_name='datos_pago',
            name='titular',
        ),
        migrations.AddField(
            model_name='datos_pago',
            name='tarjeta',
            field=models.BooleanField(null=True),
        ),
    ]
