# Generated by Django 4.2.5 on 2023-12-04 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_remove_datos_pago_caducidad_remove_datos_pago_cs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajereclamacion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
