# Generated by Django 4.2.5 on 2023-11-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False, null=True)),
                ('calle', models.CharField(max_length=200, null=True)),
                ('ciudad', models.CharField(max_length=200, null=True)),
                ('numero', models.CharField(max_length=200, null=True)),
                ('provincia', models.CharField(max_length=200, null=True)),
                ('pais', models.CharField(max_length=200, null=True)),
                ('codigo_postal', models.CharField(max_length=200, null=True)),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta'), ('CONTRA_REEMBOLSO', 'Contra Reembolso')], max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente')),
            ],
        ),
    ]
