# Generated by Django 4.2.5 on 2023-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='puerta',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
