# Generated by Django 4.2.5 on 2023-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_pedido_puerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_envio',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
