# Generated by Django 4.2.5 on 2023-11-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_pedido_precio_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
