# Generated by Django 4.2.5 on 2023-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
