# Generated by Django 4.2.5 on 2023-12-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_pedido_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tienda',
            field=models.BooleanField(null=True),
        ),
    ]
